// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

type fallbackDevelopers interface {
	SignUp(err error) bool
	SignIn(err error) bool
	RefreshToken(err error) bool
	GetDeveloper(err error) bool
	UpdateDeveloper(err error) bool
}
