// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

import (
	"context"
	"fmt"

	"github.com/ascenmmo/multiplayer-game-servers/clients/suppliers/jsonrpc"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
)

type ClientDevelopers struct {
	*ClientJsonRPC
}

type retDevelopersSignUp = func(token string, refresh string, err error)
type retDevelopersSignIn = func(token string, refresh string, err error)
type retDevelopersRefreshToken = func(newToken string, newRefresh string, err error)
type retDevelopersGetDeveloper = func(developer types.Developer, err error)
type retDevelopersUpdateDeveloper = func(err error)

func (cli *ClientDevelopers) SignUp(ctx context.Context, developer types.Developer) (token string, refresh string, err error) {

	request := requestDevelopersSignUp{Developer: developer}
	var response responseDevelopersSignUp
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "developers.signup", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return response.Token, response.Refresh, err
}

func (cli *ClientDevelopers) ReqSignUp(ctx context.Context, callback retDevelopersSignUp, developer types.Developer) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "developers.signup",
		Params:  requestDevelopersSignUp{Developer: developer},
	}}
	if callback != nil {
		var response responseDevelopersSignUp
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(response.Token, response.Refresh, err)
		}
	}
	return
}

func (cli *ClientDevelopers) SignIn(ctx context.Context, developer types.Developer) (token string, refresh string, err error) {

	request := requestDevelopersSignIn{Developer: developer}
	var response responseDevelopersSignIn
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "developers.signin", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return response.Token, response.Refresh, err
}

func (cli *ClientDevelopers) ReqSignIn(ctx context.Context, callback retDevelopersSignIn, developer types.Developer) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "developers.signin",
		Params:  requestDevelopersSignIn{Developer: developer},
	}}
	if callback != nil {
		var response responseDevelopersSignIn
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(response.Token, response.Refresh, err)
		}
	}
	return
}

func (cli *ClientDevelopers) RefreshToken(ctx context.Context, token string, refresh string) (newToken string, newRefresh string, err error) {

	request := requestDevelopersRefreshToken{
		Refresh: refresh,
		Token:   token,
	}
	var response responseDevelopersRefreshToken
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "developers.refreshtoken", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return response.NewToken, response.NewRefresh, err
}

func (cli *ClientDevelopers) ReqRefreshToken(ctx context.Context, callback retDevelopersRefreshToken, token string, refresh string) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "developers.refreshtoken",
		Params: requestDevelopersRefreshToken{
			Refresh: refresh,
			Token:   token,
		},
	}}
	if callback != nil {
		var response responseDevelopersRefreshToken
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(response.NewToken, response.NewRefresh, err)
		}
	}
	return
}

func (cli *ClientDevelopers) GetDeveloper(ctx context.Context, token string) (developer types.Developer, err error) {

	request := requestDevelopersGetDeveloper{Token: token}
	var response responseDevelopersGetDeveloper
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "developers.getdeveloper", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return response.Developer, err
}

func (cli *ClientDevelopers) ReqGetDeveloper(ctx context.Context, callback retDevelopersGetDeveloper, token string) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "developers.getdeveloper",
		Params:  requestDevelopersGetDeveloper{Token: token},
	}}
	if callback != nil {
		var response responseDevelopersGetDeveloper
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(response.Developer, err)
		}
	}
	return
}

func (cli *ClientDevelopers) UpdateDeveloper(ctx context.Context, token string, developer types.Developer) (err error) {

	request := requestDevelopersUpdateDeveloper{
		Developer: developer,
		Token:     token,
	}
	var response responseDevelopersUpdateDeveloper
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "developers.updatedeveloper", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return err
}

func (cli *ClientDevelopers) ReqUpdateDeveloper(ctx context.Context, callback retDevelopersUpdateDeveloper, token string, developer types.Developer) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "developers.updatedeveloper",
		Params: requestDevelopersUpdateDeveloper{
			Developer: developer,
			Token:     token,
		},
	}}
	if callback != nil {
		var response responseDevelopersUpdateDeveloper
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(err)
		}
	}
	return
}
