// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

type fallbackDevTools interface {
	CreateGame(err error) bool
	GameAddOwner(err error) bool
	GameRemoveOwner(err error) bool
	UpdateGame(err error) bool
	DeleteGame(err error) bool
	GetMyGames(err error) bool
	GetGameByGameID(err error) bool
	TurnOnServerInGame(err error) bool
	TurnOffServerInGame(err error) bool
}
