// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

import (
	"context"
	"fmt"

	"github.com/ascenmmo/multiplayer-game-servers/clients/suppliers/jsonrpc"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type ClientDevToolsServer struct {
	*ClientJsonRPC
}

type retDevToolsServerAddServer = func(err error)
type retDevToolsServerGetServers = func(servers []types.Server, err error)
type retDevToolsServerDeleteServers = func(err error)

func (cli *ClientDevToolsServer) AddServer(ctx context.Context, token string, name string, address string) (err error) {

	request := requestDevToolsServerAddServer{
		Address: address,
		Name:    name,
		Token:   token,
	}
	var response responseDevToolsServerAddServer
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "devtoolsserver.addserver", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return err
}

func (cli *ClientDevToolsServer) ReqAddServer(ctx context.Context, callback retDevToolsServerAddServer, token string, name string, address string) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "devtoolsserver.addserver",
		Params: requestDevToolsServerAddServer{
			Address: address,
			Name:    name,
			Token:   token,
		},
	}}
	if callback != nil {
		var response responseDevToolsServerAddServer
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(err)
		}
	}
	return
}

func (cli *ClientDevToolsServer) GetServers(ctx context.Context, token string) (servers []types.Server, err error) {

	request := requestDevToolsServerGetServers{Token: token}
	var response responseDevToolsServerGetServers
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "devtoolsserver.getservers", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return response.Servers, err
}

func (cli *ClientDevToolsServer) ReqGetServers(ctx context.Context, callback retDevToolsServerGetServers, token string) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "devtoolsserver.getservers",
		Params:  requestDevToolsServerGetServers{Token: token},
	}}
	if callback != nil {
		var response responseDevToolsServerGetServers
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(response.Servers, err)
		}
	}
	return
}

func (cli *ClientDevToolsServer) DeleteServers(ctx context.Context, token string, serverID uuid.UUID) (err error) {

	request := requestDevToolsServerDeleteServers{
		ServerID: serverID,
		Token:    token,
	}
	var response responseDevToolsServerDeleteServers
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "devtoolsserver.deleteservers", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return err
}

func (cli *ClientDevToolsServer) ReqDeleteServers(ctx context.Context, callback retDevToolsServerDeleteServers, token string, serverID uuid.UUID) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "devtoolsserver.deleteservers",
		Params: requestDevToolsServerDeleteServers{
			ServerID: serverID,
			Token:    token,
		},
	}}
	if callback != nil {
		var response responseDevToolsServerDeleteServers
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(err)
		}
	}
	return
}
