// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

type fallbackDevToolsServer interface {
	AddServer(err error) bool
	GetServers(err error) bool
	DeleteServers(err error) bool
}
