// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

type fallbackDevToolsConnections interface {
	CreateRoom(err error) bool
	GetRoomsAll(err error) bool
	JoinRoomByID(err error) bool
	RemoveRoomByID(err error) bool
	GetRoomsConnectionUrls(err error) bool
}
