// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

import (
	"context"
	"fmt"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/clients/multiplayer/hasher"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/clients/multiplayer/jsonrpc"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type ClientDevToolsGameConfigs struct {
	*ClientJsonRPC
}

type retDevToolsGameConfigsCreateOrUpdateConfig = func(err error)
type retDevToolsGameConfigsGetGameConfig = func(configs types.GameConfigs, err error)

func (cli *ClientDevToolsGameConfigs) CreateOrUpdateConfig(ctx context.Context, token string, configs types.GameConfigs) (err error) {

	request := requestDevToolsGameConfigsCreateOrUpdateConfig{
		Configs: configs,
		Token:   token,
	}
	var response responseDevToolsGameConfigsCreateOrUpdateConfig
	var rpcResponse *jsonrpc.ResponseRPC
	cacheKey, _ := hasher.Hash(request)
	rpcResponse, err = cli.rpc.Call(ctx, "devtoolsgameconfigs.createorupdateconfig", request)
	var fallbackCheck func(error) bool
	if cli.fallbackDevToolsGameConfigs != nil {
		fallbackCheck = cli.fallbackDevToolsGameConfigs.CreateOrUpdateConfig
	}
	if rpcResponse != nil && rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
	}
	if err = cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response); err != nil {
		return
	}
	return err
}

func (cli *ClientDevToolsGameConfigs) ReqCreateOrUpdateConfig(ctx context.Context, callback retDevToolsGameConfigsCreateOrUpdateConfig, token string, configs types.GameConfigs) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "devtoolsgameconfigs.createorupdateconfig",
		Params: requestDevToolsGameConfigsCreateOrUpdateConfig{
			Configs: configs,
			Token:   token,
		},
	}}
	if callback != nil {
		var response responseDevToolsGameConfigsCreateOrUpdateConfig
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			cacheKey, _ := hasher.Hash(request.rpcRequest.Params)
			var fallbackCheck func(error) bool
			if cli.fallbackDevToolsGameConfigs != nil {
				fallbackCheck = cli.fallbackDevToolsGameConfigs.CreateOrUpdateConfig
			}
			if rpcResponse != nil && rpcResponse.Error != nil {
				if cli.errorDecoder != nil {
					err = cli.errorDecoder(rpcResponse.Error.Raw())
				} else {
					err = fmt.Errorf(rpcResponse.Error.Message)
				}
			}
			callback(cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response))
		}
	}
	return
}

func (cli *ClientDevToolsGameConfigs) GetGameConfig(ctx context.Context, token string, gameID uuid.UUID) (configs types.GameConfigs, err error) {

	request := requestDevToolsGameConfigsGetGameConfig{
		GameID: gameID,
		Token:  token,
	}
	var response responseDevToolsGameConfigsGetGameConfig
	var rpcResponse *jsonrpc.ResponseRPC
	cacheKey, _ := hasher.Hash(request)
	rpcResponse, err = cli.rpc.Call(ctx, "devtoolsgameconfigs.getgameconfig", request)
	var fallbackCheck func(error) bool
	if cli.fallbackDevToolsGameConfigs != nil {
		fallbackCheck = cli.fallbackDevToolsGameConfigs.GetGameConfig
	}
	if rpcResponse != nil && rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
	}
	if err = cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response); err != nil {
		return
	}
	return response.Configs, err
}

func (cli *ClientDevToolsGameConfigs) ReqGetGameConfig(ctx context.Context, callback retDevToolsGameConfigsGetGameConfig, token string, gameID uuid.UUID) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "devtoolsgameconfigs.getgameconfig",
		Params: requestDevToolsGameConfigsGetGameConfig{
			GameID: gameID,
			Token:  token,
		},
	}}
	if callback != nil {
		var response responseDevToolsGameConfigsGetGameConfig
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			cacheKey, _ := hasher.Hash(request.rpcRequest.Params)
			var fallbackCheck func(error) bool
			if cli.fallbackDevToolsGameConfigs != nil {
				fallbackCheck = cli.fallbackDevToolsGameConfigs.GetGameConfig
			}
			if rpcResponse != nil && rpcResponse.Error != nil {
				if cli.errorDecoder != nil {
					err = cli.errorDecoder(rpcResponse.Error.Raw())
				} else {
					err = fmt.Errorf(rpcResponse.Error.Message)
				}
			}
			callback(response.Configs, cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response))
		}
	}
	return
}
