// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

type fallbackDevToolsGameConfigs interface {
	CreateOrUpdateConfig(err error) bool
	GetGameConfig(err error) bool
	GetGameResultConfigPreview(err error) bool
}
