// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

type fallbackDevTools interface {
	CreateGame(err error) bool
	GameAddOwner(err error) bool
	GameRemoveUser(err error) bool
	UpdateGame(err error) bool
	GetMyGames(err error) bool
	GetGameByGameID(err error) bool
	TurnOnServerInGame(err error) bool
	TurnOffServerInGame(err error) bool
}
