// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

type fallbackDevToolsClient interface {
	SignUp(err error) bool
	SignIn(err error) bool
	RefreshToken(err error) bool
	GetClient(err error) bool
	UpdateClient(err error) bool
	GetGameSaves(err error) bool
	SetGameSaves(err error) bool
	DeleteGameSaves(err error) bool
}
