// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

import (
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type requestDevToolsServerAddServer struct {
	Token   string `json:"token"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

// Formal exchange type, please do not delete.
type responseDevToolsServerAddServer struct{}

type requestDevToolsServerGetServers struct {
	Token string `json:"token"`
}

type responseDevToolsServerGetServers struct {
	Servers []types.Server `json:"servers"`
}

type requestDevToolsServerDeleteServers struct {
	Token    string    `json:"token"`
	ServerID uuid.UUID `json:"serverID"`
}

// Formal exchange type, please do not delete.
type responseDevToolsServerDeleteServers struct{}
