// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

import (
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type requestDevToolsCreateGame struct {
	Token string     `json:"token"`
	Game  types.Game `json:"game"`
}

type responseDevToolsCreateGame struct {
	Id uuid.UUID `json:"id"`
}

type requestDevToolsGameAddOwner struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
	UserID uuid.UUID `json:"userID"`
}

// Formal exchange type, please do not delete.
type responseDevToolsGameAddOwner struct{}

type requestDevToolsGameRemoveOwner struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
	UserID uuid.UUID `json:"userID"`
}

// Formal exchange type, please do not delete.
type responseDevToolsGameRemoveOwner struct{}

type requestDevToolsUpdateGame struct {
	Token   string     `json:"token"`
	GameID  uuid.UUID  `json:"gameID"`
	NewGame types.Game `json:"newGame"`
}

type responseDevToolsUpdateGame struct {
	Id uuid.UUID `json:"id"`
}

type requestDevToolsDeleteGame struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
}

// Formal exchange type, please do not delete.
type responseDevToolsDeleteGame struct{}

type requestDevToolsGetMyGames struct {
	Token string `json:"token"`
}

type responseDevToolsGetMyGames struct {
	Games []types.Game `json:"games"`
}

type requestDevToolsGetGameByGameID struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
}

type responseDevToolsGetGameByGameID struct {
	Game types.Game `json:"game"`
}

type requestDevToolsTurnOnServerInGame struct {
	Token    string    `json:"token"`
	ServerID uuid.UUID `json:"serverID"`
	GameId   uuid.UUID `json:"gameId"`
}

// Formal exchange type, please do not delete.
type responseDevToolsTurnOnServerInGame struct{}

type requestDevToolsTurnOffServerInGame struct {
	Token    string    `json:"token"`
	ServerID uuid.UUID `json:"serverID"`
	GameId   uuid.UUID `json:"gameId"`
}

// Formal exchange type, please do not delete.
type responseDevToolsTurnOffServerInGame struct{}
