// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package multiplayer

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/clients/multiplayer/cb"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/clients/multiplayer/jsonrpc"
	"os"
	"strconv"
	"time"
)

type ClientJsonRPC struct {
	name string

	rpc     *jsonrpc.ClientRPC
	rpcOpts []jsonrpc.Option

	cache cache

	cbCfg cb.Settings
	cb    *cb.CircuitBreaker

	fallbackTTL                 time.Duration
	fallbackDevTools            fallbackDevTools
	fallbackDevToolsClient      fallbackDevToolsClient
	fallbackDevToolsConnections fallbackDevToolsConnections
	fallbackDevToolsGameConfigs fallbackDevToolsGameConfigs
	fallbackDevToolsServer      fallbackDevToolsServer
	fallbackDevelopers          fallbackDevelopers

	errorDecoder ErrorDecoder
}

func New(endpoint string, opts ...Option) (cli *ClientJsonRPC) {

	hostname, _ := os.Hostname()
	cli = &ClientJsonRPC{
		errorDecoder: defaultErrorDecoder,
		fallbackTTL:  time.Hour * 24,
		name:         hostname + "_" + "github.com/ascenmmo/multiplayer-game-servers",
	}
	cli.applyOpts(opts)
	cli.rpc = jsonrpc.NewClient(endpoint, cli.rpcOpts...)
	cli.cb = cb.NewCircuitBreaker("github.com/ascenmmo/multiplayer-game-servers", cli.cbCfg)
	return
}

func (cli *ClientJsonRPC) DevTools() *ClientDevTools {
	return &ClientDevTools{ClientJsonRPC: cli}
}

func (cli *ClientJsonRPC) DevToolsClient() *ClientDevToolsClient {
	return &ClientDevToolsClient{ClientJsonRPC: cli}
}

func (cli *ClientJsonRPC) DevToolsConnections() *ClientDevToolsConnections {
	return &ClientDevToolsConnections{ClientJsonRPC: cli}
}

func (cli *ClientJsonRPC) DevToolsGameConfigs() *ClientDevToolsGameConfigs {
	return &ClientDevToolsGameConfigs{ClientJsonRPC: cli}
}

func (cli *ClientJsonRPC) DevToolsServer() *ClientDevToolsServer {
	return &ClientDevToolsServer{ClientJsonRPC: cli}
}

func (cli *ClientJsonRPC) Developers() *ClientDevelopers {
	return &ClientDevelopers{ClientJsonRPC: cli}
}

func (cli *ClientJsonRPC) proceedResponse(ctx context.Context, httpErr error, cacheKey uint64, fallbackCheck func(error) bool, rpcResponse *jsonrpc.ResponseRPC, methodResponse interface{}) (err error) {

	err = cli.cb.Execute(func() (err error) {
		if httpErr != nil {
			return httpErr
		}
		return rpcResponse.GetObject(&methodResponse)
	}, cb.IsSuccessful(func(err error) (success bool) {
		if fallbackCheck != nil {
			return fallbackCheck(err)
		}
		if success = err == nil; success {
			if cli.cache != nil && cacheKey != 0 {
				_ = cli.cache.SetTTL(ctx, strconv.FormatUint(cacheKey, 10), methodResponse, cli.fallbackTTL)
			}
		}
		return
	}), cb.Fallback(func(err error) error {
		if cli.cache != nil && cacheKey != 0 {
			_, _, err = cli.cache.GetTTL(ctx, strconv.FormatUint(cacheKey, 10), &methodResponse)
		}
		return err
	}))
	return
}
