// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/gofiber/fiber/v2"
)

type httpDevelopers struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverDevelopers
	base             multiplayer.Developers
}

func NewDevelopers(svcDevelopers multiplayer.Developers) (srv *httpDevelopers) {

	srv = &httpDevelopers{
		base: svcDevelopers,
		svc:  newServerDevelopers(svcDevelopers),
	}
	return
}

func (http *httpDevelopers) Service() *serverDevelopers {
	return http.svc
}

func (http *httpDevelopers) WithLog() *httpDevelopers {
	http.svc.WithLog()
	return http
}

func (http *httpDevelopers) WithTrace() *httpDevelopers {
	http.svc.WithTrace()
	return http
}

func (http *httpDevelopers) WithMetrics() *httpDevelopers {
	http.svc.WithMetrics()
	return http
}

func (http *httpDevelopers) WithErrorHandler(handler ErrorHandler) *httpDevelopers {
	http.errorHandler = handler
	return http
}

func (http *httpDevelopers) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/developers", http.serveBatch)
	route.Post("/api/v1/developers/signUp", http.serveSignUp)
	route.Post("/api/v1/developers/signIn", http.serveSignIn)
	route.Post("/api/v1/developers/refreshToken", http.serveRefreshToken)
	route.Post("/api/v1/developers/getDeveloper", http.serveGetDeveloper)
	route.Post("/api/v1/developers/updateDeveloper", http.serveUpdateDeveloper)
}
