// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
)

type DevelopersSignUp func(ctx context.Context, developer types.Developer) (token string, refresh string, err error)
type DevelopersSignIn func(ctx context.Context, developer types.Developer) (token string, refresh string, err error)
type DevelopersRefreshToken func(ctx context.Context, token string, refresh string) (newToken string, newRefresh string, err error)
type DevelopersGetDeveloper func(ctx context.Context, token string) (developer types.Developer, err error)
type DevelopersUpdateDeveloper func(ctx context.Context, token string, developer types.Developer) (err error)

type MiddlewareDevelopers func(next multiplayer.Developers) multiplayer.Developers

type MiddlewareDevelopersSignUp func(next DevelopersSignUp) DevelopersSignUp
type MiddlewareDevelopersSignIn func(next DevelopersSignIn) DevelopersSignIn
type MiddlewareDevelopersRefreshToken func(next DevelopersRefreshToken) DevelopersRefreshToken
type MiddlewareDevelopersGetDeveloper func(next DevelopersGetDeveloper) DevelopersGetDeveloper
type MiddlewareDevelopersUpdateDeveloper func(next DevelopersUpdateDeveloper) DevelopersUpdateDeveloper
