// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"

	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceDevelopers struct {
	next multiplayer.Developers
}

func traceMiddlewareDevelopers(next multiplayer.Developers) multiplayer.Developers {
	return &traceDevelopers{next: next}
}

func (svc traceDevelopers) SignUp(ctx context.Context, developer types.Developer) (token string, refresh string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "developers.signUp")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.SignUp(ctx, developer)
}

func (svc traceDevelopers) SignIn(ctx context.Context, developer types.Developer) (token string, refresh string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "developers.signIn")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.SignIn(ctx, developer)
}

func (svc traceDevelopers) RefreshToken(ctx context.Context, token string, refresh string) (newToken string, newRefresh string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "developers.refreshToken")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.RefreshToken(ctx, token, refresh)
}

func (svc traceDevelopers) GetDeveloper(ctx context.Context, token string) (developer types.Developer, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "developers.getDeveloper")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.GetDeveloper(ctx, token)
}

func (svc traceDevelopers) UpdateDeveloper(ctx context.Context, token string, developer types.Developer) (err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "developers.updateDeveloper")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.UpdateDeveloper(ctx, token, developer)
}
