// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"

type requestDevelopersSignUp struct {
	Developer types.Developer `json:"developer"`
}

type responseDevelopersSignUp struct {
	Token   string `json:"token"`
	Refresh string `json:"refresh"`
}

type requestDevelopersSignIn struct {
	Developer types.Developer `json:"developer"`
}

type responseDevelopersSignIn struct {
	Token   string `json:"token"`
	Refresh string `json:"refresh"`
}

type requestDevelopersRefreshToken struct {
	Token   string `json:"token"`
	Refresh string `json:"refresh"`
}

type responseDevelopersRefreshToken struct {
	NewToken   string `json:"newToken"`
	NewRefresh string `json:"newRefresh"`
}

type requestDevelopersGetDeveloper struct {
	Token string `json:"token"`
}

type responseDevelopersGetDeveloper struct {
	Developer types.Developer `json:"developer"`
}

type requestDevelopersUpdateDeveloper struct {
	Token     string          `json:"token"`
	Developer types.Developer `json:"developer"`
}

// Formal exchange type, please do not delete.
type responseDevelopersUpdateDeveloper struct{}
