// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
	"github.com/opentracing/opentracing-go"
)

type traceDevToolsServer struct {
	next multiplayer.DevToolsServer
}

func traceMiddlewareDevToolsServer(next multiplayer.DevToolsServer) multiplayer.DevToolsServer {
	return &traceDevToolsServer{next: next}
}

func (svc traceDevToolsServer) AddServer(ctx context.Context, token string, name string, address string) (err error) {
	span := opentracing.SpanFromContext(ctx)
	span.SetTag("method", "AddServer")
	return svc.next.AddServer(ctx, token, name, address)
}

func (svc traceDevToolsServer) GetServers(ctx context.Context, token string) (servers []types.Server, err error) {
	span := opentracing.SpanFromContext(ctx)
	span.SetTag("method", "GetServers")
	return svc.next.GetServers(ctx, token)
}

func (svc traceDevToolsServer) DeleteServers(ctx context.Context, token string, serverID uuid.UUID) (err error) {
	span := opentracing.SpanFromContext(ctx)
	span.SetTag("method", "DeleteServers")
	return svc.next.DeleteServers(ctx, token, serverID)
}
