// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type DevToolsConnectionsCreateRoom func(ctx context.Context, token string, gameID uuid.UUID) (newToken string, err error)
type DevToolsConnectionsGetRoomsAll func(ctx context.Context, token string, gameID uuid.UUID) (rooms []types.Room, err error)
type DevToolsConnectionsJoinRoomByID func(ctx context.Context, token string, gameID uuid.UUID, roomID uuid.UUID) (newToken string, err error)
type DevToolsConnectionsRemoveRoomByID func(ctx context.Context, token string, gameID uuid.UUID, roomID uuid.UUID) (err error)
type DevToolsConnectionsGetRoomsConnectionUrls func(ctx context.Context, token string) (connectionsServer []types.ConnectionServer, err error)

type MiddlewareDevToolsConnections func(next multiplayer.DevToolsConnections) multiplayer.DevToolsConnections

type MiddlewareDevToolsConnectionsCreateRoom func(next DevToolsConnectionsCreateRoom) DevToolsConnectionsCreateRoom
type MiddlewareDevToolsConnectionsGetRoomsAll func(next DevToolsConnectionsGetRoomsAll) DevToolsConnectionsGetRoomsAll
type MiddlewareDevToolsConnectionsJoinRoomByID func(next DevToolsConnectionsJoinRoomByID) DevToolsConnectionsJoinRoomByID
type MiddlewareDevToolsConnectionsRemoveRoomByID func(next DevToolsConnectionsRemoveRoomByID) DevToolsConnectionsRemoveRoomByID
type MiddlewareDevToolsConnectionsGetRoomsConnectionUrls func(next DevToolsConnectionsGetRoomsConnectionUrls) DevToolsConnectionsGetRoomsConnectionUrls
