// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/transport/viewer"
	"github.com/google/uuid"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"time"
)

type loggerDevToolsConnections struct {
	next multiplayer.DevToolsConnections
}

func loggerMiddlewareDevToolsConnections() MiddlewareDevToolsConnections {
	return func(next multiplayer.DevToolsConnections) multiplayer.DevToolsConnections {
		return &loggerDevToolsConnections{next: next}
	}
}

func (m loggerDevToolsConnections) CreateRoom(ctx context.Context, token string, gameID uuid.UUID, serverType string) (newToken string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "DevToolsConnections").Str("method", "createRoom").Logger()
	defer func(begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"request": viewer.Sprintf("%+v", requestDevToolsConnectionsCreateRoom{
					GameID:     gameID,
					ServerType: serverType,
					Token:      token,
				}),
				"response": viewer.Sprintf("%+v", responseDevToolsConnectionsCreateRoom{NewToken: newToken}),
			}
			ev.Fields(fields).Str("took", time.Since(begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createRoom")
			return
		}
		logger.Info().Func(logHandle).Msg("call createRoom")
	}(time.Now())
	return m.next.CreateRoom(ctx, token, gameID, serverType)
}

func (m loggerDevToolsConnections) GetRoomsAll(ctx context.Context, token string, gameID uuid.UUID) (rooms []types.Room, err error) {
	logger := log.Ctx(ctx).With().Str("service", "DevToolsConnections").Str("method", "getRoomsAll").Logger()
	defer func(begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"request": viewer.Sprintf("%+v", requestDevToolsConnectionsGetRoomsAll{
					GameID: gameID,
					Token:  token,
				}),
				"response": viewer.Sprintf("%+v", responseDevToolsConnectionsGetRoomsAll{Rooms: rooms}),
			}
			ev.Fields(fields).Str("took", time.Since(begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getRoomsAll")
			return
		}
		logger.Info().Func(logHandle).Msg("call getRoomsAll")
	}(time.Now())
	return m.next.GetRoomsAll(ctx, token, gameID)
}

func (m loggerDevToolsConnections) JoinRoomByID(ctx context.Context, token string, gameID uuid.UUID, roomID uuid.UUID) (newToken string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "DevToolsConnections").Str("method", "joinRoomByID").Logger()
	defer func(begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"request": viewer.Sprintf("%+v", requestDevToolsConnectionsJoinRoomByID{
					GameID: gameID,
					RoomID: roomID,
					Token:  token,
				}),
				"response": viewer.Sprintf("%+v", responseDevToolsConnectionsJoinRoomByID{NewToken: newToken}),
			}
			ev.Fields(fields).Str("took", time.Since(begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call joinRoomByID")
			return
		}
		logger.Info().Func(logHandle).Msg("call joinRoomByID")
	}(time.Now())
	return m.next.JoinRoomByID(ctx, token, gameID, roomID)
}

func (m loggerDevToolsConnections) RemoveRoomByID(ctx context.Context, token string, gameID uuid.UUID, roomID uuid.UUID) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "DevToolsConnections").Str("method", "removeRoomByID").Logger()
	defer func(begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"request": viewer.Sprintf("%+v", requestDevToolsConnectionsRemoveRoomByID{
					GameID: gameID,
					RoomID: roomID,
					Token:  token,
				}),
				"response": viewer.Sprintf("%+v", responseDevToolsConnectionsRemoveRoomByID{}),
			}
			ev.Fields(fields).Str("took", time.Since(begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call removeRoomByID")
			return
		}
		logger.Info().Func(logHandle).Msg("call removeRoomByID")
	}(time.Now())
	return m.next.RemoveRoomByID(ctx, token, gameID, roomID)
}

func (m loggerDevToolsConnections) GetRoomsConnectionUrls(ctx context.Context, token string) (connectionsServer []types.ConnectionServer, err error) {
	logger := log.Ctx(ctx).With().Str("service", "DevToolsConnections").Str("method", "getRoomsConnectionUrls").Logger()
	defer func(begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"request":  viewer.Sprintf("%+v", requestDevToolsConnectionsGetRoomsConnectionUrls{Token: token}),
				"response": viewer.Sprintf("%+v", responseDevToolsConnectionsGetRoomsConnectionUrls{ConnectionsServer: connectionsServer}),
			}
			ev.Fields(fields).Str("took", time.Since(begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getRoomsConnectionUrls")
			return
		}
		logger.Info().Func(logHandle).Msg("call getRoomsConnectionUrls")
	}(time.Now())
	return m.next.GetRoomsConnectionUrls(ctx, token)
}
