// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type requestDevToolsGameConfigsCreateOrUpdateConfig struct {
	Token   string            `json:"token"`
	Configs types.GameConfigs `json:"configs"`
}

// Formal exchange type, please do not delete.
type responseDevToolsGameConfigsCreateOrUpdateConfig struct{}

type requestDevToolsGameConfigsGetGameConfig struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
}

type responseDevToolsGameConfigsGetGameConfig struct {
	Configs types.GameConfigs `json:"configs"`
}

type requestDevToolsGameConfigsGetGameResultConfigPreview struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
}

type responseDevToolsGameConfigsGetGameResultConfigPreview struct {
	GameResult types.GameConfigResults `json:"gameResult"`
}
