// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"encoding/json"
	"strings"
	"sync"

	"github.com/ascenmmo/multiplayer-game-servers/pkg/transport/context"
	"github.com/gofiber/fiber/v2"
	"github.com/rs/zerolog/log"
)

func (http *httpDevToolsClient) serveSignUp(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "signup", http.signUp)
}
func (http *httpDevToolsClient) signUp(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientSignUp
	var response responseDevToolsClientSignUp

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.signUp").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "signup",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	response.Token, response.Refresh, err = http.svc.SignUp(methodCtx, request.Client)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveSignIn(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "signin", http.signIn)
}
func (http *httpDevToolsClient) signIn(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientSignIn
	var response responseDevToolsClientSignIn

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.signIn").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "signin",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	response.Token, response.Refresh, err = http.svc.SignIn(methodCtx, request.Client)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveRefreshToken(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "refreshtoken", http.refreshToken)
}
func (http *httpDevToolsClient) refreshToken(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientRefreshToken
	var response responseDevToolsClientRefreshToken

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.refreshToken").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "refreshtoken",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	if _token := string(ctx.Request().Header.Peek("Token")); _token != "" {
		var token string
		token = _token
		request.Token = token
	}
	if _refresh := string(ctx.Request().Header.Peek("RefreshToken")); _refresh != "" {
		var refresh string
		refresh = _refresh
		request.Refresh = refresh
	}

	response.NewToken, response.NewRefresh, err = http.svc.RefreshToken(methodCtx, request.Token, request.Refresh)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveGetClient(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "getclient", http.getClient)
}
func (http *httpDevToolsClient) getClient(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientGetClient
	var response responseDevToolsClientGetClient

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.getClient").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "getclient",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	if _token := string(ctx.Request().Header.Peek("Token")); _token != "" {
		var token string
		token = _token
		request.Token = token
	}

	response.Client, err = http.svc.GetClient(methodCtx, request.Token, request.GameID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveUpdateClient(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "updateclient", http.updateClient)
}
func (http *httpDevToolsClient) updateClient(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientUpdateClient
	var response responseDevToolsClientUpdateClient

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.updateClient").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "updateclient",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	if _token := string(ctx.Request().Header.Peek("Token")); _token != "" {
		var token string
		token = _token
		request.Token = token
	}

	err = http.svc.UpdateClient(methodCtx, request.Token, request.Client)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveGetGameSaves(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "getgamesaves", http.getGameSaves)
}
func (http *httpDevToolsClient) getGameSaves(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientGetGameSaves
	var response responseDevToolsClientGetGameSaves

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.getGameSaves").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "getgamesaves",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	if _token := string(ctx.Request().Header.Peek("Token")); _token != "" {
		var token string
		token = _token
		request.Token = token
	}

	response.GameSaves, err = http.svc.GetGameSaves(methodCtx, request.Token)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveSetGameSaves(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "setgamesaves", http.setGameSaves)
}
func (http *httpDevToolsClient) setGameSaves(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientSetGameSaves
	var response responseDevToolsClientSetGameSaves

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.setGameSaves").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "setgamesaves",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	if _token := string(ctx.Request().Header.Peek("Token")); _token != "" {
		var token string
		token = _token
		request.Token = token
	}

	err = http.svc.SetGameSaves(methodCtx, request.Token, request.GameSaves)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) serveDeleteGameSaves(ctx *fiber.Ctx) (err error) {
	return http._serveMethod(ctx, "deletegamesaves", http.deleteGameSaves)
}
func (http *httpDevToolsClient) deleteGameSaves(ctx *fiber.Ctx, requestBase baseJsonRPC) (responseBase *baseJsonRPC) {

	var err error
	var request requestDevToolsClientDeleteGameSaves
	var response responseDevToolsClientDeleteGameSaves

	methodCtx := ctx.UserContext()
	methodCtx = log.Ctx(methodCtx).With().Str("method", "devToolsClient.deleteGameSaves").Logger().WithContext(methodCtx)

	defer func() {
		ctx.SetUserContext(context.WithCtx(methodCtx, MethodCallMeta{

			Err:      err,
			Method:   "deletegamesaves",
			Request:  &request,
			Response: &response,
			Service:  "devtoolsclient",
		}))
	}()
	if requestBase.Params != nil {
		if err = json.Unmarshal(requestBase.Params, &request); err != nil {
			return makeErrorResponseJsonRPC(requestBase.ID, parseError, "request body could not be decoded: "+err.Error(), nil)
		}
	}
	if requestBase.Version != Version {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "incorrect protocol version: "+requestBase.Version, nil)
	}

	if _token := string(ctx.Request().Header.Peek("Token")); _token != "" {
		var token string
		token = _token
		request.Token = token
	}

	err = http.svc.DeleteGameSaves(methodCtx, request.Token)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		code := internalError
		if errCoder, ok := err.(withErrorCode); ok {
			code = errCoder.Code()
		}
		return makeErrorResponseJsonRPC(requestBase.ID, code, err.Error(), err)
	}
	responseBase = &baseJsonRPC{
		ID:      requestBase.ID,
		Version: Version,
	}
	if responseBase.Result, err = json.Marshal(response); err != nil {
		return makeErrorResponseJsonRPC(requestBase.ID, parseError, "response body could not be encoded: "+err.Error(), nil)
	}

	return
}
func (http *httpDevToolsClient) _serveMethod(ctx *fiber.Ctx, methodName string, methodHandler methodJsonRPC) (err error) {

	methodHTTP := ctx.Method()
	if methodHTTP != fiber.MethodPost {
		ctx.Response().SetStatusCode(fiber.StatusMethodNotAllowed)
		if _, err = ctx.WriteString("only POST method supported"); err != nil {
			return
		}
	}
	var request baseJsonRPC
	var response *baseJsonRPC
	if err = json.Unmarshal(ctx.Body(), &request); err != nil {
		return sendResponse(ctx, makeErrorResponseJsonRPC([]byte("\"0\""), parseError, "request body could not be decoded: "+err.Error(), nil))
	}
	methodNameOrigin := request.Method
	method := strings.ToLower(request.Method)
	if method != "" && method != methodName {
		return sendResponse(ctx, makeErrorResponseJsonRPC(request.ID, methodNotFoundError, "invalid method "+methodNameOrigin, nil))
	}
	response = methodHandler(ctx, request)
	if response != nil {
		return sendResponse(ctx, response)
	}
	return
}
func (http *httpDevToolsClient) doBatch(ctx *fiber.Ctx, requests []baseJsonRPC) (responses jsonrpcResponses) {

	if len(requests) > http.maxBatchSize {
		responses.append(makeErrorResponseJsonRPC(nil, invalidRequestError, "batch size exceeded", nil))
		return
	}
	if strings.EqualFold(ctx.Get("X-Sync-On"), "true") {
		for _, request := range requests {
			response := http.doSingleBatch(ctx, request)
			if request.ID != nil {
				responses.append(response)
			}
		}
		return
	}
	var wg sync.WaitGroup
	batchSize := http.maxParallelBatch
	if len(requests) < batchSize {
		batchSize = len(requests)
	}
	callCh := make(chan baseJsonRPC, batchSize)
	responses = make(jsonrpcResponses, 0, len(requests))
	for i := 0; i < batchSize; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for request := range callCh {
				response := http.doSingleBatch(ctx, request)
				if request.ID != nil {
					responses.append(response)
				}
			}
		}()
	}
	for idx := range requests {
		callCh <- requests[idx]
	}
	close(callCh)
	wg.Wait()
	return
}
func (http *httpDevToolsClient) serveBatch(ctx *fiber.Ctx) (err error) {

	var single bool
	var requests []baseJsonRPC
	methodHTTP := ctx.Method()
	if methodHTTP != fiber.MethodPost {
		ctx.Response().SetStatusCode(fiber.StatusMethodNotAllowed)
		if _, err = ctx.WriteString("only POST method supported"); err != nil {
			return
		}
		return
	}
	if err = json.Unmarshal(ctx.Body(), &requests); err != nil {
		var request baseJsonRPC
		if err = json.Unmarshal(ctx.Body(), &request); err != nil {
			return sendResponse(ctx, makeErrorResponseJsonRPC([]byte("\"0\""), parseError, "request body could not be decoded: "+err.Error(), nil))
		}
		single = true
		requests = append(requests, request)
	}
	if single {
		return sendResponse(ctx, http.doSingleBatch(ctx, requests[0]))
	}
	return sendResponse(ctx, http.doBatch(ctx, requests))
}
func (http *httpDevToolsClient) doSingleBatch(ctx *fiber.Ctx, request baseJsonRPC) (response *baseJsonRPC) {

	methodNameOrigin := request.Method
	method := strings.ToLower(request.Method)
	switch method {
	case "signup":
		return http.signUp(ctx, request)
	case "signin":
		return http.signIn(ctx, request)
	case "refreshtoken":
		return http.refreshToken(ctx, request)
	case "getclient":
		return http.getClient(ctx, request)
	case "updateclient":
		return http.updateClient(ctx, request)
	case "getgamesaves":
		return http.getGameSaves(ctx, request)
	case "setgamesaves":
		return http.setGameSaves(ctx, request)
	case "deletegamesaves":
		return http.deleteGameSaves(ctx, request)
	default:
		return makeErrorResponseJsonRPC(request.ID, methodNotFoundError, "invalid method '"+methodNameOrigin+"'", nil)
	}
}
