// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type DevToolsGameConfigsCreateOrUpdateConfig func(ctx context.Context, token string, configs types.GameConfigs) (err error)
type DevToolsGameConfigsGetGameConfig func(ctx context.Context, token string, gameID uuid.UUID) (configs types.GameConfigs, err error)
type DevToolsGameConfigsGetGameResultConfigPreview func(ctx context.Context, token string, gameID uuid.UUID) (gameResult types.GameConfigResults, err error)

type MiddlewareDevToolsGameConfigs func(next multiplayer.DevToolsGameConfigs) multiplayer.DevToolsGameConfigs

type MiddlewareDevToolsGameConfigsCreateOrUpdateConfig func(next DevToolsGameConfigsCreateOrUpdateConfig) DevToolsGameConfigsCreateOrUpdateConfig
type MiddlewareDevToolsGameConfigsGetGameConfig func(next DevToolsGameConfigsGetGameConfig) DevToolsGameConfigsGetGameConfig
type MiddlewareDevToolsGameConfigsGetGameResultConfigPreview func(next DevToolsGameConfigsGetGameResultConfigPreview) DevToolsGameConfigsGetGameResultConfigPreview
