// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
)

type requestDevToolsConnectionsCreateRoom struct {
	Token      string    `json:"token"`
	GameID     uuid.UUID `json:"gameID"`
	ServerType string    `json:"serverType"`
}

type responseDevToolsConnectionsCreateRoom struct {
	NewToken string `json:"newToken"`
}

type requestDevToolsConnectionsGetRoomsAll struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
}

type responseDevToolsConnectionsGetRoomsAll struct {
	Rooms []types.Room `json:"rooms"`
}

type requestDevToolsConnectionsJoinRoomByID struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
	RoomID uuid.UUID `json:"roomID"`
}

type responseDevToolsConnectionsJoinRoomByID struct {
	NewToken string `json:"newToken"`
}

type requestDevToolsConnectionsRemoveRoomByID struct {
	Token  string    `json:"token"`
	GameID uuid.UUID `json:"gameID"`
	RoomID uuid.UUID `json:"roomID"`
}

// Formal exchange type, please do not delete.
type responseDevToolsConnectionsRemoveRoomByID struct{}

type requestDevToolsConnectionsGetRoomsConnectionUrls struct {
	Token string `json:"token"`
}

type responseDevToolsConnectionsGetRoomsConnectionUrls struct {
	ConnectionsServer []types.ConnectionServer `json:"connectionsServer"`
}
