// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer/types"
	"github.com/google/uuid"
	"github.com/opentracing/opentracing-go"
)

type traceDevToolsGameConfigs struct {
	next multiplayer.DevToolsGameConfigs
}

func traceMiddlewareDevToolsGameConfigs(next multiplayer.DevToolsGameConfigs) multiplayer.DevToolsGameConfigs {
	return &traceDevToolsGameConfigs{next: next}
}

func (svc traceDevToolsGameConfigs) CreateOrUpdateConfig(ctx context.Context, token string, configs types.GameConfigs) (err error) {
	span := opentracing.SpanFromContext(ctx)
	span.SetTag("method", "CreateOrUpdateConfig")
	return svc.next.CreateOrUpdateConfig(ctx, token, configs)
}

func (svc traceDevToolsGameConfigs) GetGameConfig(ctx context.Context, token string, gameID uuid.UUID) (configs types.GameConfigs, err error) {
	span := opentracing.SpanFromContext(ctx)
	span.SetTag("method", "GetGameConfig")
	return svc.next.GetGameConfig(ctx, token, gameID)
}
