// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/ascenmmo/multiplayer-game-servers/pkg/multiplayer"
	"github.com/gofiber/fiber/v2"
)

type httpDevToolsServer struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverDevToolsServer
	base             multiplayer.DevToolsServer
}

func NewDevToolsServer(svcDevToolsServer multiplayer.DevToolsServer) (srv *httpDevToolsServer) {

	srv = &httpDevToolsServer{
		base: svcDevToolsServer,
		svc:  newServerDevToolsServer(svcDevToolsServer),
	}
	return
}

func (http *httpDevToolsServer) Service() *serverDevToolsServer {
	return http.svc
}

func (http *httpDevToolsServer) WithLog() *httpDevToolsServer {
	http.svc.WithLog()
	return http
}

func (http *httpDevToolsServer) WithTrace() *httpDevToolsServer {
	http.svc.WithTrace()
	return http
}

func (http *httpDevToolsServer) WithMetrics() *httpDevToolsServer {
	http.svc.WithMetrics()
	return http
}

func (http *httpDevToolsServer) WithErrorHandler(handler ErrorHandler) *httpDevToolsServer {
	http.errorHandler = handler
	return http
}

func (http *httpDevToolsServer) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/devToolsServer", http.serveBatch)
	route.Post("/api/v1/devToolsServer/addServer", http.serveAddServer)
	route.Post("/api/v1/devToolsServer/getServers", http.serveGetServers)
	route.Post("/api/v1/devToolsServer/deleteServers", http.serveDeleteServers)
}
